### ISSUE TITLE
add search command for viewing thumbs up playlist

### ISSUE THREAD

**Issue by kufii** [kufii/Audioshield-PlayMusic#12]
I'm thinking `-fav`

**Comment by Keavon** [comment]
That sounds like a good command because it's short and doesn't result in differences between American and British spellings.

**Comment by Keavon** [comment]
This is implemented with `pm.getFavorites` and the returned order is good as-is, so it does not need to be sorted.

**Comment by Keavon** [comment]
Here's the start of the implementation:

```
var getFavoriteTracks = function(q, callback) {
    run(function*(gen) {
        try {
            pm.getFavorites((err, data) => {
                callback(null, data.track)
            });
        } catch (err) {
            callback(err);
        }
    });
};
```

And you'll need to replace lines `46` and `47` with the following:

```
soundcloudResponse.id = track.nid || track.id;
soundcloudResponse.artwork_url = track.albumArtRef ? track.albumArtRef[0].url : track.imageBaseUrl;
```

And of course you need to add a `case` for `"fav"`.

With the way the code is currently set up, `-fav` alone returns no results because it does not contain a space, so some random string must be included after it like `-fav foo` to make it return the favorites. I could fix that myself, but I thought you might want to implement this idea:

`-fav` alone returns your most recent favorite songs, but `-fav query` returns search results for songs filtered to those which you have favorited.

Hope this helps!

**Comment by kufii** [comment]
Thanks, modified it a bit and completed
