### ISSUE TITLE
Generate proper ssl certificate

### ISSUE THREAD

**Issue by kufii** [kufii/Audioshield-PlayMusic#8]
also should provide a way to easily update said certificate after it expires, preferably automatically

**Comment by Keavon** [comment]
Would it be possible to use https://github.com/node-nock/nock in place of Fiddler? Since it's just a Node.js package, it would greatly simplify the installation process and reduce the need to start separate programs. I could be misinterpreting what that package does, but it looks like it's used to intercept and modify HTTP requests like Fiddler.

**Comment by kufii** [comment]
I've actually already made significant steps to removing the fiddler dependency. I made a HTTP proxy server, all I need to do is make a proper certificate and I can remove it

**Comment by Keavon** [comment]
Does that mean you're hosting that proxy server online (which could be slow and you'll have to pay for it), or is it run locally in the Node.js application? Does it still rely on editing the `hosts` file to redirect traffic from the SoundCloud domain to the proxy server?

**Comment by kufii** [comment]
It's a locally run node proxy server and doesn't rely on the hosts file. It intercepts all traffic and redirects it if it's going to the SoundCloud api and the user agent is from audioshield

**Comment by Keavon** [comment]
That sounds perfect! Does that also mean that the only thing that needs to run is the Node.js process and no other software? If that were the case, it could run silently in the background at all times and work with standard Audioshield!
